# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      some-input:
        required: true
        type: string

jobs:
  generate-string:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.generate.outputs.result }}
    steps:
      - name: Generate string
        id: generate
          #run: echo "::set-output name=result:: Hello from the shared workflow"
        run: echo "This is a test"
