# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      some-input:
        required: true
        type: string
  workflow_call:
    inputs:
      some-input:
        required: true
        type: string

jobs:
  generate-string:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.generate.outputs.result }}
    steps:
      - name: Create file with string
        run: |
          echo "This is the string being passed: ${{ inputs.some-input }}." > string
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: testing-artifact
          path: artifact
